name: Environment setup and build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: self-hosted
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Install kas
        run: pip3 install kas

  clone_meta_qcom:
    needs: setup-environment
    runs-on: self-hosted
    steps:
      - name: Ensure Git is configured
        run: |
          git config --global advice.detachedHead false
          git config --global credential.helper store

      - name: Clone meta-qcom repo with retry
        run: |
          for i in {1..3}; do
            git clone --depth 1 https://github.com/qualcomm-linux/meta-qcom.git -b master && break
            echo "Retrying clone ($i)..."
            sleep 10
          done
          cd meta-qcom/ci

      - name: Install kas in meta-qcom/ci
        run: sudo pip3 install kas

      - name: Run kas shell and bitbake
        run: |
          cd meta-qcom/ci
          kas shell qcs9100-ride-sx.yml:qcom-distro.yml
          bitbake qcom-multimedia-proprietary-image

