name: IRIS App Injection

on:
  workflow_dispatch:
  push:
    branches: 
      - test-workflow

jobs:
  inject:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y e2fsprogs

      - name: Run IRIS injection inside Docker
        shell: bash
        run: |
          echo "🚀 Running IRIS injection inside Docker..."

          USER_ID=$(id -u)
          GROUP_ID=$(id -g)
          USER=$(whoami)
          WORKSPACE=${{ github.workspace }}/..
          USER_HOME="/home/$USER"

          docker run \
            --rm \
            --user ${USER_ID}:${GROUP_ID} \
            -v ${WORKSPACE}:${USER_HOME}/workspace \
            -w ${USER_HOME}/workspace \
            --privileged \
            kas_dependencies \
            bash -c "
              set -e
              echo '🔧 Injecting IRIS App...'
              bash ci/inject_iris_app.sh \
                --image-dir meta-qcom/build/tmp/deploy/images/qcs8300-ride-sx \
                --machine qcs8300-ride-sx
            "
