name: IRIS App Injection

on:
  workflow_dispatch:
  push:
    branches:
      - test-workflow

jobs:
  inject:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        machines: [qcs9100-ride-sx, qcs8300-ride-sx, qcs6490-rb3gen2-core-kit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Link external image directory into workspace
        run: |
          ln -s /local/mnt/workspace/manigurr/images/images ${{ github.workspace }}/external_images

      - name: Copy all image files to workspace
        run: |
          echo "
