name: pre_merge
description: |
  Orchestrates pre-merge CI for the video-driver repository without a matrix
  in the caller workflow. Builds and tests using reusable workflows.

on:
  push:
    branches:
      - workflow_2
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - workflow_2
    paths-ignore:
      - '.github/**'

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: qualcomm-linux-stg/video-driver/.github/workflows/sync-and-build.yml@workflow_2
    secrets: inherit
    with:
      docker_image: ghcr.io/qualcomm-linux-stg/kmake-video-image:ver.1.0

  test:
    needs: build
    uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@workflow_2
    secrets: inherit
    with:
      docker_image: kmake-video-image:ver.1.0
  #  test-qcs9100:
  #   needs: build
  #   uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@workflow_2
  #   secrets: inherit
  #   with:
  #     docker_image: ghcr.io/qualcomm-linux-stg/kmake-video-image:ver.1.0
  #     machine: qcs9100-ride-sx
  #     lavaname: qcs9100-ride-oss
  #     presigned_artifact_name: presigned_urls.json

  # test-qcs8300:
  #   needs: build
  #   uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@workflow_2
  #   secrets: inherit
  #   with:
  #     docker_image: ghcr.io/qualcomm-linux-stg/kmake-video-image:ver.1.0
  #     machine: qcs8300-ride-sx
  #     lavaname: qcs8300-ride-oss
  #     presigned_artifact_name: presigned_urls.json

  # test-qcs6490:
  #   needs: build
  #   uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@workflow_2
  #   secrets: inherit
  #   with:
  #     docker_image: ghcr.io/qualcomm-linux-stg/kmake-video-image:ver.1.0
  #     machine: qcs6490-rb3gen2
  #     lavaname: qcs6490-rb3gen2-oss
  #     presigned_artifact_name: presigned_urls.json