name: post_merge

run-name: Post Merge Build and LAVA Test

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: read
  actions: write

concurrency:
  group: post-merge-build-and-test
  cancel-in-progress: false

jobs:
  loading:
    name: Load build configuration
    uses: ./.github/workflows/loading.yml
    with:
      event_name: ${{ github.event_name }}

  build:
    name: Build
    needs:
      - loading

    uses: ./.github/workflows/sync-and-build.yml

    with:
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      docker_image: kmake-image:ver.1.0
      commit_sha: ${{ github.sha }}

  lava-test:
    name: Run LAVA tests
    needs:
      - loading
      - build

    uses: ./.github/workflows/test.yml

    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      commit_sha: ${{ github.sha }}
      build_run_id: ${{ github.run_id }}
      build_repository: ${{ github.repository }}

    secrets:
      LAVA_OSS_TOKEN: ${{ secrets.LAVA_OSS_TOKEN }}
      LAVA_OSS_USER: ${{ secrets.LAVA_OSS_USER }}