name: post_merge_weekly

on:
  schedule:
    # Every Monday and Thursday at 02:30 UTC
    - cron: "* * * * *"

jobs:
  loading:
    uses: qualcomm-linux-stg/video-driver/.github/workflows/loading.yml@meta-qcom
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}

  build:
    needs: loading
    uses: qualcomm-linux-stg/video-driver/.github/workflows/sync-and-build.yml@meta-qcom
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}

  lava-test:
    needs: [loading, build]
    uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@meta-qcom
    secrets: inherit
    with:
      commit_sha: ${{ github.sha }}
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}
