name: Post Merge Weekly

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  loading:
    # We call the reusable workflow
    uses: qualcomm-linux-stg/video-driver/.github/workflows/loading.yml@video.qclinux.0.0
    secrets: inherit

  build:
    needs: loading
    uses: qualcomm-linux-stg/video-driver/.github/workflows/sync-and-build.yml@video.qclinux.0.0
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}

  lava-test:
    needs: [loading, build]
    uses: qualcomm-linux-stg/video-driver/.github/workflows/test.yml@video.qclinux.0.0
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}