name: pre_merge
run-name: Pre Merge Workflow
on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - video.qclinux.0.0

jobs:
  loading:
    uses: qualcomm-linux-stg/video-driver/.github/workflows/loading.yml@format
    secrets: inherit

  build:
    needs: loading
    uses: qualcomm-linux-stg/video-driver/.github/workflows/build.yml@format
    secrets: inherit
    with:
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      docker_image: kmake-image:ver.1.0